#!/bin/sh

if [ "$2" = "usage" ] || [ $# = 1 ] 
then
  echo "  Undo item:"
  curcmd=`basename $0`
  echo "    $curcmd [ID]"
  echo "      undo task identified by ID"
  echo ""
  exit
fi

# Remove x and completion date
sed -i "$2s/^x [0-9-]\+ //" $TODO_FILE
# Print line as we leave it
head -$2 $TODO_FILE | tail -1
# Give feedback
echo "TODO: $2 undone."
